import { LEGAL_DOCUMENTS_UPDATED_RU } from "@/features/store-moderation/block-02-legal/legal-version";
import { getPrivacyPolicyUrl, getSupportEmail, getTermsOfUseUrl } from "@/lib/legal";

/** Текст для копирования в App Store Connect → App Review Information → Notes. */
export function buildAppStoreReviewNotesTemplate(): string {
  const lines = [
    "=== App Store Connect — Notes for Review (заполните поля) ===",
    "",
    "Primary test account:",
    "  Login (phone/email): ",
    "  Password: ",
    "  Invite / referral code (if required): ",
    "",
    "Second test account (for chat/call checks):",
    "  Login (phone/email): ",
    "  Password: ",
    "",
    "Review environment:",
    "  Backend base URL: ",
    "  Region restrictions: none / list",
    "  Feature flags used in this build: ",
    "",
    "Steps for reviewer (2–3 min):",
    "  1) Log in with the primary test account above.",
    "  2) Open feed — open any post.",
    "  3) Open a chat — send a text message.",
    "  4) Use second account to reply and (if in scope) place an audio/video call.",
    "  5) Open Stories from the feed strip (if visible).",
    "  6) UGC safety: long-press a message → «Пожаловаться»; post ⋮ menu → «Пожаловаться»; profile ⋮ → «Пожаловаться» / «Заблокировать».",
    "  7) Stories: open a story → ⋮ (actions) → «Пожаловаться на сториз».",
    "  8) Account deletion: Settings → Delete account (confirmation dialog shown).",
    "",
    "Moderation:",
    "  Users can report content in the app. Our team reviews reports in the admin panel (target SLA: within 24 hours).",
    "  Story reports open in-app from admin via link to /posts?storyId=<uuid> (same visibility rules as users).",
    "",
    "Google Play (internal testing / Play Console notes — align with Data safety & UGC declarations):",
    "  Same in-app reporting flows as on iOS (posts, messages, profiles, stories, comments).",
    "  Admin queue: Operations → User reports; SLA target matches the line above.",
    "",
    "Public URLs (Privacy / Terms / support):",
    `  Privacy: ${getPrivacyPolicyUrl()}`,
    `  Terms of use: ${getTermsOfUseUrl()}`,
    `  Support email: ${getSupportEmail()}`,
    "",
    "In-app legal (same build as submitted):",
    "  Settings → More (Прочее) → Privacy Policy / Terms of use; also linked on the login / registration screen.",
    "  SPA routes (if same origin as app): /privacy and /terms open inside the app without Safari.",
    `  Legal documents last updated (in-app text): ${LEGAL_DOCUMENTS_UPDATED_RU}`,
    "",
    "Known reviewer pitfalls (fill before submit):",
    "  - If registration is invite-only, include a valid invite code above.",
    "  - If any feature is geo-limited or role-limited, list exact constraints.",
    "  - If calls are in scope, ensure both test users are online and callable.",
    "",
  ];
  return lines.join("\n");
}
