export {
  getDb,
  getPool,
  closeDb,
  ensureUserColumns,
  ensurePlatformSettingsCompat,
  ensurePlatformRegistrationPhoneVerificationColumn,
  ensureAdminMediaStudioSchema,
  ensurePostsFeedSchema,
  ensureStoriesFeedBoostColumns,
  ensureStoryCaptionNotificationSchema,
  ensureChatVibeSchema,
  ensureCallTranscriptsSchema,
  ensureChatCodesSchema,
  ensureContentReportsSchema,
} from "./client";
